### ISSUE TITLE
Adding a "-" & "+" Buttions

### ISSUE THREAD

**Issue by XeroZar** [CmdrCody51/OctoPrint-MarlinSlider#6]
### Is your feature request related to a problem? Please describe.

The slider for the fan control is too tedious to control, especially when you want to increase fan speeds by 1%.

### Describe the solution you'd like

![FN1](https://github.com/CmdrCody51/OctoPrint-MarlinSlider/assets/107234166/290c4bbd-a64c-432f-94e2-904ffa086ca9)
Is it possible to add 2 buttons to the side of the fan slider (please see pic) to be able to increase/decrease fan speed by 1% increments? 

### Describe alternatives you've considered

None.

### Additional context

![FN1](https://github.com/CmdrCody51/OctoPrint-MarlinSlider/assets/107234166/4b180bc6-ac55-4eeb-b575-f3641e131081)

**Comment by CmdrCody51** [comment]
I got some changes coming up in March (see other issue) so I can throw this in too. I will probably use the same arrows as on the XY right and left instead of the -+ symbols. Remember though, you still have to click Fan Speed button to send it. I just have to check how they will effect the display.
The most accurate method will still be to drop into the Terminal tab and send your M106 S(0-255) if you want finer control.

**Comment by XeroZar** [comment]
Hi, thank you... Its just for what I am trying to do, those 2 buttons will help instead of the slider... I find the slider good but when I split my screen with like 4 windows, the slider is hard to get small increments hence the buttons. But again thank you, will wait for the update.
